version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.max_content_length=1024mb
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=5t4ch380x!
      - KIBANA_SYSTEM_PASSWORD=5t4ch380x!
      - APM_SYSTEM_PASSWORD=5t4ch380x!
      - REMOTE_MONITORING_USER_PASSWORD=5t4ch380x!
      - LOGSTASH_SYSTEM_PASSWORD=L0g5t4ch3!
      - BEATS_SYSTEM_PASSWORD=L0g5t4ch3!
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.3
    ports:
      - "5044:5044"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
